<?php

declare(strict_types=1);

namespace TheNguyen\CMS\Taxonomy\Translation;

use TheNguyen\CMS\Translation\Content\LocalizedFieldDefinition;

/**
 * The canonical localized field vocabulary for taxonomy term translations (Phase 9.2B).
 *
 * This is the single source of truth for WHICH fields a term translation carries and
 * HOW each maps to a platform {@see LocalizedFieldDefinition}. Every taxonomy adoption
 * stage (driver 9.2C, read/write adapters 9.2D/E, admin 9.2F, revision 9.2G) consumes
 * this vocabulary, so Category, Tag, and every future/plugin taxonomy share ONE field
 * contract with no per-taxonomy code.
 *
 * The fields mirror the `cms_term_translations` columns exactly. Role mapping vs
 * Content (see TAXONOMY-TRANSLATION-CONTRACT.md §Field mapping):
 *
 *   name             → title role   (required in the default locale, ≤255)
 *   slug             → slug role    (optional; auto-generated by TaxonomyManager)
 *   description      → body role     (optional, HTML; sanitized by TaxonomyManager)
 *   meta_title       → SEO title     (optional, ≤255)
 *   meta_description → SEO description (optional)
 *
 * There is intentionally NO `meta_keywords` (terms have no such column) and NO
 * separate excerpt/content split (terms carry a single `description`).
 *
 * Pure/static — defining or reading this vocabulary has NO runtime side effects.
 */
final class TaxonomyTranslationFields
{
    public const NAME = 'name';

    public const SLUG = 'slug';

    public const DESCRIPTION = 'description';

    public const META_TITLE = 'meta_title';

    public const META_DESCRIPTION = 'meta_description';

    /**
     * The canonical ordered field list (== the `cms_term_translations` localized columns).
     *
     * @return array<int, string>
     */
    public static function all(): array
    {
        return [self::NAME, self::SLUG, self::DESCRIPTION, self::META_TITLE, self::META_DESCRIPTION];
    }

    /**
     * The fields a taxonomy driver persists. Identical to {@see all()} — declared
     * separately so a future driver can reference an explicit "driver field set"
     * without implying the admin renders all of them.
     *
     * @return array<int, string>
     */
    public static function driverFields(): array
    {
        return self::all();
    }

    /**
     * The canonical localized field definitions, keyed by field name. Consumed by the
     * admin seam (validation/slug-preview/fallback) and any SDK adopter.
     *
     * @return array<string, LocalizedFieldDefinition>
     */
    public static function definitions(): array
    {
        return [
            self::NAME => LocalizedFieldDefinition::title(self::NAME, ['max_length' => 255]),
            self::SLUG => LocalizedFieldDefinition::slug(self::SLUG, ['required_default' => false, 'max_length' => 255]),
            self::DESCRIPTION => LocalizedFieldDefinition::richContent(self::DESCRIPTION),
            self::META_TITLE => LocalizedFieldDefinition::seoTitle(self::META_TITLE, ['max_length' => 255]),
            self::META_DESCRIPTION => LocalizedFieldDefinition::seoDescription(self::META_DESCRIPTION),
        ];
    }
}
