<?php

namespace App\Providers\Filament;

use App\Filament\Admin\Widgets\CmsInfoWidget;
use App\Http\Controllers\Admin\MediaSearchController;
use App\Http\Middleware\SetCmsAdminLocale;
use Filament\Http\Middleware\Authenticate;
use Filament\Http\Middleware\AuthenticateSession;
use Filament\Http\Middleware\DisableBladeIconComponents;
use Filament\Http\Middleware\DispatchServingFilamentEvent;
use Filament\Navigation\NavigationGroup;
use Filament\Pages\Dashboard;
use Filament\Panel;
use Filament\PanelProvider;
use Filament\Support\Colors\Color;
use Filament\View\PanelsRenderHook;
use Filament\Widgets\AccountWidget;
use Filament\Widgets\FilamentInfoWidget;
use Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse;
use Illuminate\Cookie\Middleware\EncryptCookies;
use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken;
use Illuminate\Routing\Middleware\SubstituteBindings;
use Illuminate\Session\Middleware\StartSession;
use Illuminate\Support\Facades\Route;
use Illuminate\View\Middleware\ShareErrorsFromSession;

class AdminPanelProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            ->default()
            ->id('admin')
            // Admin URL segment is configurable (collected by the web installer);
            // changing it requires a route cache clear.
            ->path((string) config('cms.admin_path', 'admin'))
            ->login()
            ->colors([
                'primary' => Color::Amber,
            ])
            // Custom admin theme (Filament v5): the vendor base scans only
            // Filament's own views, so Tailwind utilities used in first-party
            // and plugin admin Blade views are generated by this theme's
            // @source globs. See resources/css/filament/admin/theme.css.
            ->viteTheme('resources/css/filament/admin/theme.css')
            ->discoverResources(in: app_path('Filament/Admin/Resources'), for: 'App\Filament\Admin\Resources')
            ->discoverPages(in: app_path('Filament/Admin/Pages'), for: 'App\Filament\Admin\Pages')
            ->pages([
                Dashboard::class,
            ])
            ->discoverWidgets(in: app_path('Filament/Admin/Widgets'), for: 'App\Filament\Admin\Widgets')
            // Generic: register Filament resources/pages declared by any active
            // CMS plugin's manifest. Knows nothing about specific plugins.
            ->plugin(\TheNguyen\CMS\Filament\PluginResourceRegistrar::make())
            // Groups are keyed by their stable English identity (resources match
            // by array key), while the DISPLAY label is a lazy closure translated
            // via tn_trans() at render time — so admin nav groups follow the
            // current locale without changing how items are grouped.
            ->navigationGroups([
                'Content' => NavigationGroup::make(fn (): string => tn_trans('Content')),
                'Media' => NavigationGroup::make(fn (): string => tn_trans('Media')),
                // Ecommerce plugin groups (IA-1), positioned directly below Media in
                // a deliberate order. Labels resolve from the plugin's own "ecommerce"
                // translation hint; a plugin cannot order sidebar groups itself, so the
                // order is owned here. Matching is by group label at render time.
                // Tax + Settings are contributed by the plugin under their own label
                // namespaces; ordering them here keeps them adjacent to the other
                // Ecommerce groups instead of floating below CMS (E8 IA cleanup).
                // Formerly-floating plugin-owned groups (IA-1). A plugin cannot order
                // sidebar groups itself, so — exactly like the Ecommerce groups above —
                // Core owns the order here while each group's DISPLAY label mirrors the
                // label the plugin's own resources render, so items match by label at
                // render time and follow the current locale. No plugin code is touched.
                'Literature' => NavigationGroup::make(fn (): string => __('Literature')),
                'Music' => NavigationGroup::make(fn (): string => __('Music')),
                'Knowledge Graph' => NavigationGroup::make(fn (): string => __('Knowledge Graph')),
                'Timeline' => NavigationGroup::make(fn (): string => __('Timeline')),
                'Citations' => NavigationGroup::make(fn (): string => __('Citations')),
                'Appearance' => NavigationGroup::make(fn (): string => tn_trans('Appearance')),
                'Plugins' => NavigationGroup::make(fn (): string => tn_trans('Plugins')),
                // Developer + migration tooling sit just below Plugins (IA-1). The
                // Developer label mirrors ACF's own translation; the migration group is
                // a locale-invariant literal because that plugin declares it as a raw
                // static string rather than a translated key.
                'TNCMS Migration' => NavigationGroup::make(fn (): string => 'TNCMS Migration'),
                'Users' => NavigationGroup::make(fn (): string => tn_trans('Users')),
                'CMS' => NavigationGroup::make(fn (): string => tn_trans('CMS')),
            ])
            // Dashboard widgets are filterable so plugins can contribute their
            // own (cms.admin.dashboard.widgets, v1.0.0-beta.7.1.12.2).
            ->widgets($this->adminArrayFilter('cms.admin.dashboard.widgets', [
                CmsInfoWidget::class,
                AccountWidget::class,
                FilamentInfoWidget::class,
            ]))
            // Extra navigation items contributed by plugins (cms.admin.navigation).
            ->navigationItems($this->adminArrayFilter('cms.admin.navigation', []))
            ->middleware([
                EncryptCookies::class,
                AddQueuedCookiesToResponse::class,
                StartSession::class,
                AuthenticateSession::class,
                ShareErrorsFromSession::class,
                VerifyCsrfToken::class,
                SubstituteBindings::class,
                DisableBladeIconComponents::class,
                DispatchServingFilamentEvent::class,
                // Align the framework locale with the CMS locale so Filament's
                // own built-in strings (Create/Save/Delete/Search/pagination)
                // follow the same language as the TN CMS interface (beta.5.1).
                SetCmsAdminLocale::class,
            ])
            ->authMiddleware([
                Authenticate::class,
            ])
            // Backend language switcher in the topbar. Lets a logged-in user pick
            // the admin UI language; the choice is persisted to their
            // user.admin_locale by SetCmsAdminLocale. Renders nothing for
            // single-language sites. (v1.0.0-beta.7.1.10)
            ->renderHook(
                PanelsRenderHook::TOPBAR_END,
                fn (): string => view('filament.admin.locale-switcher')->render(),
            )
            // Plugin-injected admin head assets (cms.admin.assets, an action;
            // plugins echo <style>/<script>/<meta>). v1.0.0-beta.7.1.12.2.
            ->renderHook(
                PanelsRenderHook::HEAD_END,
                fn (): string => $this->renderAdminAssets(),
            )
            // Asset Registry (v1.0.0-beta.7.1.13.1): enqueued admin scripts/
            // modules + inline scripts, rendered before </body>. Never throws.
            ->renderHook(
                PanelsRenderHook::BODY_END,
                fn (): string => $this->renderAdminRegistryScripts(),
            )
            // Authenticated JSON endpoint backing the MediaLibrarySelect grid's
            // server-side image search (logo/favicon/featured-image pickers), so
            // large media libraries stay fully searchable instead of being capped
            // to the first page loaded into the grid. Inherits this panel's auth
            // middleware. Route name: filament.admin.cms-media-search.
            ->authenticatedRoutes(function (): void {
                Route::get('cms-media-search', MediaSearchController::class)
                    ->name('cms-media-search');
            });
    }

    /**
     * Apply an admin-level ARRAY filter (navigation items / dashboard widgets)
     * through the hook layer. Guarded and array-safe: if the hook layer is
     * unavailable, a listener throws, or a non-array is returned, the original
     * value is used so the panel always builds. (v1.0.0-beta.7.1.12.2)
     *
     * @param  array<int, mixed>  $value
     * @return array<int, mixed>
     */
    private function adminArrayFilter(string $hook, array $value): array
    {
        try {
            if (function_exists('apply_filters') && app()->bound('cms.hooks')) {
                $filtered = apply_filters($hook, $value);

                if (is_array($filtered)) {
                    return $filtered;
                }
            }
        } catch (\Throwable) {
            // Fall through to the original value.
        }

        return $value;
    }

    /**
     * Render plugin-contributed admin head assets by capturing everything the
     * cms.admin.assets action echoes. Never throws — a broken plugin asset
     * callback must not break the admin shell. (v1.0.0-beta.7.1.12.2)
     */
    private function renderAdminAssets(): string
    {
        $html = '';

        try {
            if (function_exists('render_hook')) {
                $html .= render_hook('cms.admin.assets');
            }
        } catch (\Throwable) {
            // No assets rather than a broken admin head.
        }

        // Asset Registry (v1.0.0-beta.7.1.13.1): enqueued admin stylesheets +
        // head inline styles, in dependency order. Never throws.
        try {
            if (function_exists('render_admin_styles')) {
                $html .= render_admin_styles();
            }
        } catch (\Throwable) {
            // Fall through to whatever was already captured.
        }

        return $html;
    }

    /**
     * Render Asset Registry admin scripts before </body>. Never throws — a
     * broken registered asset must not break the admin shell.
     * (v1.0.0-beta.7.1.13.1)
     */
    private function renderAdminRegistryScripts(): string
    {
        try {
            if (function_exists('render_admin_scripts')) {
                return render_admin_scripts();
            }
        } catch (\Throwable) {
            // No scripts rather than a broken admin footer.
        }

        return '';
    }
}
